extern const GeoLayout wario_cap_001_switch_opt1[];
extern const GeoLayout warios_cap_geo[];
extern const GeoLayout warios_metal_cap_geo[];
extern const GeoLayout warios_wing_cap_geo[];
extern const GeoLayout warios_winged_metal_cap_geo[];
extern Vtx wario_cap_000_displaylist_mesh_vtx_0[58];
extern Gfx wario_cap_000_displaylist_mesh_tri_0[];
extern Vtx wario_cap_000_displaylist_mesh_vtx_1[27];
extern Gfx wario_cap_000_displaylist_mesh_tri_1[];
extern Vtx wario_cap_000_displaylist_mesh_vtx_2[20];
extern Gfx wario_cap_000_displaylist_mesh_tri_2[];
extern Vtx wario_cap_000_displaylist_mesh_vtx_3[1570];
extern Gfx wario_cap_000_displaylist_mesh_tri_3[];

extern Gfx wario_capbase[];
extern Gfx wario_capwings[];
extern Gfx wario_capmetal[];
extern Gfx wario_capmetalwings[];
extern Gfx wario_cap_000_displaylist_mesh_mat_override_wario_metal_0[];
extern Gfx wario_cap_material_revert_render_settings[];