#include "src/game/envfx_snow.h"

const GeoLayout milk_bottle_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_CULLING_RADIUS(106383),
		GEO_OPEN_NODE(),
			GEO_SHADOW(0, 180, 240),
			GEO_OPEN_NODE(),
				GEO_SWITCH_CASE(2, geo_switch_anim_state),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(4, milk_bottle_000_displaylist_mesh),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(0, milk_bottle_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, milk_bottle_material_revert_render_settings),
		GEO_DISPLAY_LIST(2, milk_bottle_material_revert_render_settings),
		GEO_DISPLAY_LIST(3, milk_bottle_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, milk_bottle_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, milk_bottle_material_revert_render_settings),
		GEO_DISPLAY_LIST(6, milk_bottle_material_revert_render_settings),
		GEO_DISPLAY_LIST(7, milk_bottle_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
